name: build-and-publish

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DCS_REGISTRY_URL }}
          username: ${{ secrets.DCS_REGISTRY_USER }}
          password: ${{ secrets.DCS_REGISTRY_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.base
          push: true
          tags: ${{ secrets.DCS_REGISTRY_URL }}/dcs/app-base:${{ github.sha }}

  helm:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v4
      - name: Package Helm Chart
        run: |
          helm lint chart
          helm package chart --destination dist
      - name: Upload Chart Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: dist/*.tgz

