# ==============================================================================
# ci-template.yaml - Universal Build & Publish Pipeline
# ==============================================================================
# 🧩 Purpose:
# This file defines a generic CI/CD pipeline for building and publishing
# Docker images and Helm Charts in Weaversoft platform.
#
# It is platform-agnostic and can be adapted for:
#   - GitHub Actions
#   - GitLab CI/CD
#   - Jenkins
#   - Azure DevOps Pipelines
#
# 📝 Requirements:
# 1. Environment variables or secrets must be provided:
#    - REGISTRY_URL          (e.g., registry.weaversoft.io)
#    - REGISTRY_USER
#    - REGISTRY_PASSWORD
# 2. Ensure Docker and Helm are installed on the runner/agent.
# ==============================================================================

stages:
  - build
  - publish
  - package

# ------------------------------------------------------------------------------
# Stage 1: Build Docker image
# ------------------------------------------------------------------------------
build_image:
  stage: build
  script:
    - echo "🔧 Logging in to registry..."
    - echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY_URL" -u "$REGISTRY_USER" --password-stdin
    
    - echo "🏗️ Building Docker image..."
    - docker build -t "$REGISTRY_URL/weaversoft/app-base:${CI_COMMIT_SHA:-latest}" -f docker/Dockerfile.base .
    
    - echo "✅ Build complete."

# ------------------------------------------------------------------------------
# Stage 2: Publish Docker image
# ------------------------------------------------------------------------------
publish_image:
  stage: publish
  script:
    - echo "📦 Pushing Docker image to registry..."
    - docker push "$REGISTRY_URL/weaversoft/app-base:${CI_COMMIT_SHA:-latest}"
  needs: [build_image]

# ------------------------------------------------------------------------------
# Stage 3: Package Helm Chart
# ------------------------------------------------------------------------------
package_chart:
  stage: package
  script:
    - echo "📦 Packaging Helm Chart..."
    - helm lint chart
    - helm package chart --destination dist
    - echo "✅ Helm chart packaged successfully."
  artifacts:
    paths:
      - dist/*.tgz
  needs: [publish_image]

# ------------------------------------------------------------------------------
# 🧠 Notes for CI system integration
# ------------------------------------------------------------------------------
# For GitHub Actions:
#   - Convert 'stages' to 'jobs' and use 'runs-on' + 'steps' instead of 'stage/script'.
#   - Replace ${CI_COMMIT_SHA} with ${{ github.sha }}.
#
# For GitLab CI/CD:
#   - Save this file as '.gitlab-ci.yml' (works almost as-is).
#
# For Jenkins:
#   - Use each stage as a pipeline 'stage' block within a Jenkinsfile.
#
# For Azure DevOps:
#   - Convert each 'stage' to a separate job under 'jobs:'.
#
# ⚙️ Optional Enhancements:
#   - Add security scans (Trivy, Grype)
#   - Add tests before build
#   - Add 'latest' tag push automatically
#   - Push Helm chart to an OCI Helm registry if used